#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
source "$script_dir/lib.sh"

run_scenario_test lib identity_collision
run_scenario_test lib contract_file_publish_no_overwrite_destination_already_exists
run_scenario_test lib contract_file_publish_different_destination_returns_typed_collision
run_scenario_test lib different_byte_destination_race_keeps_loser_failed_without_metadata_write
run_scenario_test lib live_photo_motion_with_size_suffixed_primary_stem_is_on_disk_skipped
run_scenario_test lib live_photo_motion_with_identity_suffixed_primary_stem_is_on_disk_skipped
run_scenario_test lib live_photo_motion_with_sanitized_identity_suffix_is_on_disk_skipped
run_scenario_test lib live_photo_motion_original_policy_with_primary_collision_is_on_disk_skipped
run_scenario_test lib current_live_photo_and_filtered_assets_do_not_read_receipts
run_scenario_test lib legacy_parent_receipt_does_not_block_current_download_pass
run_scenario_test lib numbered_live_photo_paths_remain_stable_across_restart
run_scenario_test lib album_publication_receipts_prevent_repeat_downloads_after_restart
run_scenario_test lib additional_album_receipts_reject
run_scenario_test lib import_matches_live_photo_motion_from_size_suffixed_primary_stem
run_scenario_test lib import_matches_live_photo_motion_from_sanitized_identity_suffixed_primary_stem
run_scenario_test lib pending_same_size_collision_does_not_adopt_other_assets_bare_file
run_scenario_test lib truncated_suffixed_downloaded_file_is_forwarded_not_on_disk_skipped
