#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
source "$script_dir/lib.sh"

run_scenario_test lib incremental_source_delete_prunes_pending_row_in_bounded_sync
run_scenario_test lib incremental_prunes_existing_source_deleted_pending_row_without_wide_sync
run_scenario_test lib bounded_full_sync_hydrates_live_legacy_pending_master
run_scenario_test lib bounded_full_sync_revalidates_policy_excluded_asset_after_later_deletion
run_scenario_test lib contract_unknown_provider_identity_remains_pending_without_durable_match
run_scenario_test lib contract_policy_excluded_requires_explicit_source_deletion
run_scenario_test lib pending_retry_retains_transient_legacy_hydration_failure
run_scenario_test lib issue_770_recovery
run_scenario_test lib pending_retry_deleted_sibling_does_not_tombstone_present_master_state
run_scenario_test lib approved_truncated_reconcile_retry_replaces_the_recorded_path
run_scenario_test lib truncated_repair_provider_version_change_uses_sibling
run_scenario_test lib targeted_master_only_lookup_distinguishes_live_legacy_master
run_scenario_test lib hydrate_matching_master_assets_collects_every_live_sibling
